---
# Installs a BPM
# Corresponds to docker layer https://github.com/sherl0cks/docker-bpms

- name: Set BPM Suite Artifact Facts
  set_fact:
    bpms_artifact_url: "{{ bpms_artifact_repo + '/' + bpms_artifact_name }}"
    bpms_artifact_dl_dest: "{{ '/tmp/' + bpms_artifact_name }}"

- name: Debug BPM Suite Artifact URL
  debug:
    msg: "{{ bpms_artifact_url }}"

- name: Debug BPM Suite Artifact Download Destination
  debug:
    msg: "{{ bpms_artifact_dl_dest }}"    

#- name: Download BPM Suite Artifact 
#  get_url:
#    url: "{{ bpms_artifact_url }}"
#    dest: "{{ bpms_artifact_dl_dest }}"

- name: Copy BPMSuite artifact
  copy:
    src: "{{ bpms_artifact_url }}"
    dest: "{{ bpms_artifact_dl_dest }}"

# This should overlay the BPM download over EAP, intentionally overwriting some files in the process        
- name: Extract BPM Suite
  unarchive:
    src: "{{ bpms_artifact_dl_dest }}"
    dest: "{{ eap_library_dest }}"
    creates: /opt/jboss-as/jboss-eap-6.4/bin/kie.policy
    copy: no
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"

- include: patch.yml

- include: java_opts.yml

### TODO - feels like there should be a start service here but the notify happens at the end, which is odd to me
