- hosts: default
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - centos
 #   - gnome
    - bpmsuite-workshop
  tags:
    - centos
 #   - gnome
    - bpmsuite-workshop
