- name: Reload systemd
  become: yes
  become_user: root
  command: systemctl daemon-reload

- name: Start and Enable jboss-as Service
  service:
    name: jboss-as-standalone.service
    state: started
    enabled: yes
